### ISSUE TITLE
Can we just not?

### ISSUE THREAD

**Issue by funniray** [bytixo/PirateStealer#39]
I know that this code will always still exist, but really, can we not?

You gain nothing but hurting people on the internet by making this a thing. I'm not dumb enough to fall for this, but really people? There's already a bunch of discord scam and people shouldn't have to worry about this bullshit.

Think before publishing your code and being an asshole to people dumber than you.

Use your talent to make the world a better place, not a shittier place.

Thanks,
Snow Kit#3582

**Comment by Hunolog** [comment]
I think I found a video which explains everything
[check out this](https://www.youtube.com/watch?v=bUmkdO4Y1uY)

**Comment by Hunolog** [comment]
I think i just found the perfect video which explains everything.

[check it out](https://www.youtube.com/watch?v=hfHuE0W0X9w)

**Comment by Stanley-GF** [comment]
he is telling the truth.

**Comment by funniray** [comment]
I mean really though, why actively make the world a worse place? Do you feel satisfied knowing you've yoinked discord accounts of random kids? Does that make you happy?

I can't change your mind, but just consider it

**Comment by Stanley-GF** [comment]
nop, and i'm ok with you, again, I can't do anything.

**Comment by funniray** [comment]
I mean, you can _technically_ change the `https://github.com/bytixo/PirateStealer/blob/main/src/Injection/injection` file to make the program no longer work for programs that load in external urls, just figured that the world shouldn't have to deal with open source malware anymore

**Comment by Stanley-GF** [comment]
github not workin like this. Even if I delete or change the repos owner (I alr tried), it'll continue working, I tried many times to contact Discord explaining the problem, without answer.
