### ISSUE TITLE
PirateStealer not working

### ISSUE THREAD

**Issue by Vlad2009discord** [bytixo/PirateStealer#40]
Theres a issue with the javascript versions the index.js one works like as "tasklist" and the index-win is missing "" and after "" are added the code wont do anything(compiled or uncompiled)

**Comment by bytixo** [comment]
I don't understand lol please clarify, the index-win.js is the file used to build the grabber and it work like a charm as of now, so I don't really understand your issue

**Comment by Vlad2009discord** [comment]
Wait how is the index-win.js supposed to work?

**Comment by Vlad2009discord** [comment]
Theres no info about how to use it the readme just has some credit

**Comment by bytixo** [comment]
> Wait how is the index-win.js supposed to work?

node index-win.js

**Comment by Vlad2009discord** [comment]
> wat, can you come Discord ?

I sent a message in the discord chat

**Comment by Vlad2009discord** [comment]
> > Wait how is the index-win.js supposed to work?
> 
> node index-win.js

it does nothing

**Comment by bytixo** [comment]
alr fixed
