### ISSUE TITLE
Please take this down

### ISSUE THREAD

**Issue by CorruptComputer** [bytixo/PirateStealer#41]
This is being actively used by malware I have found, please remove this repo as it is causing people to lose their Discord accounts.

https://www.virustotal.com/gui/file/44a3c5523a916091464d2ae8386d9194758a3ecdc76ed172b871f59d5dddbf81/detection

**Comment by UnidentifiedGithubDeveloper** [comment]
No shit it's being used as malware. Fixed time on the fucking internet?
