### ISSUE TITLE
Revolt isn‘t working. Make new discord please

### ISSUE THREAD

**Issue by Makschi2** [bytixo/PirateStealer#47]
Make a discord sever. You need an invite code for creating a revolt account and the one from the link isn‘t working for creating.

**Comment by bytixo** [comment]
https://revolt.chat/publicbeta

**Comment by bytixo** [comment]
we wont make any public discord server for now, if you bought premium join the revolt server, add me in friend and send payment proof

**Comment by username91234** [comment]
@bytixo whats your name i will add you
