### ISSUE TITLE
Cant log in with token that i grabbed

### ISSUE THREAD

**Issue by HjInYoMaMa** [bytixo/PirateStealer#48]
i grabbed somebody but  i cannot log in with it.

**Comment by Stanley-GF** [comment]
More infos please (token was 2FA?, version etc)

**Comment by bytixo** [comment]
> i grabbed somebody but i cannot log in with it.

if its from user got logged out embed its completly normal, you will have to wait for them to re-login

**Comment by H00Dbtoa** [comment]
I downloaded it and can’t open it like how can i run this? ( i am new to this shit so pls explain me)
