### ISSUE TITLE
not working .-.

### ISSUE THREAD

**Issue by xSalman7** [bytixo/PirateStealer#51]
![image](https://user-images.githubusercontent.com/94204655/141596729-7a445856-0390-4032-9b25-ad5bde6ba812.png)
My friend, this old one was doing really well

As for the time when the Graber token was renewed, it will not adjust for me, and I opened it when many people did not answer me with the passwords. Please, I want the old version, and thank you
I want the old version
This version is really bad

**Comment by bytixo** [comment]
its the same nothing changed, if you want to use the old one you can, just find old commits and host them

**Comment by xSalman7** [comment]
I want the old version to do well!
