### ISSUE TITLE
I cannot start the program

### ISSUE THREAD

**Issue by Cilsh** [bytixo/PirateStealer#52]
what file and how should I run it?
I ran Program.cs but the data does not come.
I have attached a screenshot of the output
![2021-11-14 (1)](https://user-images.githubusercontent.com/81519627/141678404-eda16f19-880a-4dec-b2c7-cf0a9169b7ce.png)
Tell me what's wrong?

**Comment by Stanley-GF** [comment]
https://github.com/bytixo/PirateStealer/releases/latest
