### ISSUE TITLE
This repo has been used for malicious purposes

### ISSUE THREAD

**Issue by MishaTY** [bytixo/PirateStealer#55]
Hi,
This repo has been used in a classic discord nitro scam. The scam makes users run a exe file, that grabs their token and credit card info, and then sends it to a webhook.
Link to the discord server: https://discord.gg/XthXhgmG
(Do not join)
Please take this repo down, to prevent these types of scams.
Thanks
Misha

**Comment by Stanley-GF** [comment]
Hey Misha, 
Thanks for contacting us, we gonna work on this problem tomorrow (may delete his webhook or idk) but even if we delete, 
Have a nice day
- Stanley

**Comment by nwunderly** [comment]
Lol they know it's being used maliciously, that's the idea. They literally sell a "premium" version of this.
The claim that this project is for "educational purposes" is such a joke, it's easily the largest token stealer scam project on Discord.
BTW Stanley, I reported your "undetected" code to Microsoft's Defender team recently :)

Have a nice day!

**Comment by MishaTY** [comment]
Funny that I didn't notice the Stanley part in his username LOL.
Inside of the malware's source code:
![image](https://user-images.githubusercontent.com/46088515/142509812-5b807357-f15b-4b1b-a92f-384a55c88efc.png)

**Comment by bytixo** [comment]
> Lol they know it's being used maliciously, that's the idea. They literally sell a "premium" version of this. The claim that this project is for "educational purposes" is such a joke, it's easily the largest token stealer scam project on Discord. BTW Stanley, I reported your "undetected" code to Microsoft's Defender team recently :)
> 
> Have a nice day!

we clearly don't care I'm not going to lie, reporting to any antivirus company is useless and you are missing the whole point, what could be useful is reporting this flaw to discord security team but guess what ? They don't give a damn fuck about their users, and are lucky that this flaw haven't been used by any threat actors since you can do much more harmful things that just stealing discord credentials.
